### ISSUE TITLE
HT16C22_Update_Partial()

### ISSUE THREAD

**Issue by Dm1tryA** [cch9897/HT16C22_Driver#2]
Hello.
HT16C22_Update_Partial() does not work correctly.
```
for (int i = 0; i < 44; ++i) {
    for (int j = 0; j < 4; ++j) {
      HT16C22_Write_Bit(j, i);
      //HT16C22_Update_Partial();
      //HT16C22_Update_Global();
      HAL_Delay(500);
 }
 }
```
If you use HT16C22_Update_Global(); in the code above, then all segments are displayed perfectly. But if use HT16C22_Update_Partial(); in the same code, then when j is equal to even numbers, the segments are not displayed, and when j is equal to odd, the segments are displayed correctly.

**Comment by cch9897** [comment]
This Problem should be fix in new commit. Thank you for issue.
